name: Pipeline
on:
  push:
    branches:
      - master
      - feature/ci
      - release/*

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: ['14.x','13.x','12.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Prepare
        run: |
          npm ci
      - name: Install
        env:
          # Need to set a valid env, otherwise npm complains with "Failed to replace env in config: ${NPM_TOKEN}"
          NPM_TOKEN: DUMMY
        run: |
          npx gulp ci
      - name: Test
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp test
      - name: Build
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp build
          ls -la
      - name: Version
        env:
          NPM_TOKEN: DUMMY
        run: |
          npx gulp version
      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          ls -la
          npx gulp publish
