name: Pipeline
on:
  push:
    branches:
      - master
      - feature/ci
      - release/*

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: ['14.x','13.x','12.x','10.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Build
        run: |
          npm ci
          npx gulp install
